import { importProvidersFrom } from '@angular/core';
import { NgxEditorModule } from 'ngx-editor';

export const NgxEditorItalianLocale = {
  bold: 'Grassetto',
  italic: 'Corsivo',
  underline: 'Sottolineato',
  strike: 'Barrato',
  code: 'Codice',
  heading: 'Titolo',
  'heading-smaller': 'Titolo più piccolo',
  'heading-bigger': 'Titolo più grande',
  'heading-1': 'Titolo 1',
  'heading-2': 'Titolo 2',
  'heading-3': 'Titolo 3',
  'heading-4': 'Titolo 4',
  'heading-5': 'Titolo 5',
  'heading-6': 'Titolo 6',
  text: 'Testo',
  'list-ul': 'Lista non ordinata',
  'list-ol': 'Lista ordinata',
  blockquote: 'Citazione',
  'code-block': 'Blocco di codice',
  link: 'Link',
  image: 'Immagine',
  'align-left': 'Allinea a sinistra',
  'align-center': 'Allinea al centro',
  'align-right': 'Allinea a destra',
  'align-justify': 'Giustifica',
  undo: 'Annulla',
  redo: 'Ripeti',
  clean: 'Pulisci',
  format: 'Formato',
  font: 'Carattere',
  paragraph: 'Paragrafo',
  italicize: 'Corsivizza',
  bolden: 'Grassetta',

  'strike-through': 'Barrato',
  highlight: 'Evidenzia',
  superscript: 'Apice',
  subscript: 'Pedice',
  'remove-format': 'Rimuovi formattazione',
  'insert-table': 'Inserisci tabella',
  'insert-row-above': 'Inserisci riga sopra',
  'insert-row-below': 'Inserisci riga sotto',
  'insert-column-left': 'Inserisci colonna a sinistra',
  'insert-column-right': 'Inserisci colonna a destra',
  'add-head': 'Aggiungi intestazione',
  'delete-head': 'Elimina intestazione',
  'delete-column': 'Elimina colonna',
  'delete-row': 'Elimina riga',
  'delete-table': 'Elimina tabella',
  edit: 'Modifica',
  save: 'Salva',
  cancel: 'Annulla',
  table: 'Tabella',
  row: 'Riga',
  column: 'Colonna',
  cell: 'Cella',

  video: 'Video',
  audio: 'Audio',

  'horizontal-rule': 'Linea orizzontale',
  fullscreen: 'Schermo intero',

  size: 'Dimensione',
  small: 'Piccolo',
  normal: 'Normale',
  large: 'Grande',
  huge: 'Enorme',
  align: 'Allineamento',
  left: 'Sinistra',
  center: 'Centro',
  right: 'Destra',
  justify: 'Giustifica',
  color: 'Colore',
  background: 'Sfondo',
  'text-color': 'Colore del testo',
  'background-color': 'Colore di sfondo',
  'font-size': 'Dimensione del carattere',
  'font-family': 'Famiglia del carattere',
  'line-height': 'Altezza della linea',
  'letter-spacing': 'Spaziatura delle lettere',
  indent: 'Rientro',
  outdent: 'Annulla rientro',
  'ordered-list': 'Lista ordinata',
  'unordered-list': 'Lista non ordinata',
  'todo-list': 'Lista di cose da fare',
  'check-list': 'Lista di controllo',
  quote: 'Citazione',
  'link-insert': 'Inserisci link',
  'link-edit': 'Modifica link',
  'link-remove': 'Rimuovi link',
  'image-insert': 'Inserisci immagine',
  'image-edit': 'Modifica immagine',
  'image-remove': 'Rimuovi immagine',
  'video-insert': 'Inserisci video',
  'video-edit': 'Modifica video',
  'video-remove': 'Rimuovi video',
  'audio-insert': 'Inserisci audio',
  'audio-edit': 'Modifica audio',
  'audio-remove': 'Rimuovi audio',
  'table-insert': 'Inserisci tabella',
  'table-edit': 'Modifica tabella',
  'table-remove': 'Rimuovi tabella',
  'table-row-insert-above': 'Inserisci riga sopra',
  'table-row-insert-below': 'Inserisci riga sotto',
  'table-row-delete': 'Elimina riga',
  'table-column-insert-left': 'Inserisci colonna a sinistra',
  'table-column-insert-right': 'Inserisci colonna a destra',
  'table-column-delete': 'Elimina colonna',
  'table-cell-insert-before': 'Inserisci cella prima',
  'table-cell-insert-after': 'Inserisci cella dopo',
  'table-cell-delete': 'Elimina cella',
  'table-cell-merge': 'Unisci celle',
  'table-cell-split': 'Dividi cella',
  'table-cell-align-top': 'Allinea in alto',
  'table-cell-align-middle': 'Allinea al centro',
  'table-cell-align-bottom': 'Allinea in basso',
  'table-cell-align-left': 'Allinea a sinistra',
  'table-cell-align-center': 'Allinea al centro',
  'table-cell-align-right': 'Allinea a destra',
  'table-cell-valign-top': 'Allinea in alto',
  'table-cell-valign-middle': 'Allinea al centro',
  'table-cell-valign-bottom': 'Allinea in basso',
  'exit-fullscreen': 'Esci dallo schermo intero',
  print: 'Stampa',
  help: 'Aiuto',
  'keyboard-shortcuts': 'Scorciatoie da tastiera',
  about: 'Informazioni',
  export: 'Esporta',
  'export-html': 'Esporta in HTML',
  'export-markdown': 'Esporta in Markdown',
  'export-json': 'Esporta in JSON',
  'export-text': 'Esporta in testo',
  'export-clipboard': 'Esporta negli appunti',
  import: 'Importa',
  'import-html': 'Importa da HTML',
  'import-markdown': 'Importa da Markdown',
  'import-json': 'Importa da JSON',
  'import-text': 'Importa da testo',
  'import-clipboard': 'Importa dagli appunti',
  clear: 'Pulisci',
  'select-all': 'Seleziona tutto',
  copy: 'Copia',
  cut: 'Taglia',
  paste: 'Incolla',
  delete: 'Elimina',
  find: 'Trova',
  'find-and-replace': 'Trova e sostituisci',
  'spell-check': 'Controllo ortografico',
  'auto-correct': 'Correzione automatica',
  'insert-emoji': 'Inserisci emoji',
  'insert-symbol': 'Inserisci simbolo',
  'insert-special-character': 'Inserisci carattere speciale',
  'insert-horizontal-rule': 'Inserisci linea orizzontale',
  'insert-page-break': 'Inserisci interruzione di pagina',
  'insert-date': 'Inserisci data',
  'insert-time': 'Inserisci ora',
  'insert-table-of-contents': 'Inserisci indice',
  'insert-variable': 'Inserisci variabile',
  'insert-comment': 'Inserisci commento',
  'insert-comment-reply': 'Rispondi al commento',
  'insert-comment-edit': 'Modifica commento',
  'insert-comment-remove': 'Rimuovi commento',
  'insert-comment-resolve': 'Risolvi commento',
  'insert-comment-unresolve': 'Annulla risoluzione commento',
  'insert-comment-next': 'Vai al commento successivo',
  'insert-comment-previous': 'Vai al commento precedente',
  'insert-comment-list': 'Visualizza elenco commenti',
  'insert-comment-accept-all': 'Accetta tutti i commenti',
  'insert-comment-reject-all': 'Rifiuta tutti i commenti',
  'insert-comment-delete-all': 'Elimina tutti i commenti',
  'insert-comment-remove-all': 'Rimuovi tutti i commenti',
  'insert-comment-resolve-all': 'Risolvi tutti i commenti',
  'insert-comment-unresolve-all': 'Annulla risoluzione di tutti i commenti',
  'insert-comment-next-unresolved': 'Vai al commento non risolto successivo',
  'insert-comment-previous-unresolved':
    'Vai al commento non risolto precedente',
  'insert-comment-list-unresolved': 'Visualizza elenco commenti non risolti',
  'insert-comment-accept-all-unresolved':
    'Accetta tutti i commenti non risolti',
  'insert-comment-reject-all-unresolved':
    'Rifiuta tutti i commenti non risolti',
  'insert-comment-delete-all-unresolved':
    'Elimina tutti i commenti non risolti',
  'insert-comment-remove-all-unresolved':
    'Rimuovi tutti i commenti non risolti',
  'insert-comment-resolve-all-unresolved':
    'Risolvi tutti i commenti non risolti',
  'insert-comment-unresolve-all-unresolved':
    'Annulla risoluzione di tutti i commenti non risolti',
  'insert-comment-next-resolved': 'Vai al commento risolto successivo',
  'insert-comment-previous-resolved': 'Vai al commento risolto precedente',
  'insert-comment-list-resolved': 'Visualizza elenco commenti risolti',
  'insert-comment-accept-all-resolved': 'Accetta tutti i commenti risolti',
  'insert-comment-reject-all-resolved': 'Rifiuta tutti i commenti risolti',
  'insert-comment-delete-all-resolved': 'Elimina tutti i commenti risolti',
  'insert-comment-remove-all-resolved': 'Rimuovi tutti i commenti risolti',
  'insert-comment-resolve-all-resolved': 'Risolvi tutti i commenti risolti',
  'insert-comment-unresolve-all-resolved':
    'Annulla risoluzione di tutti i commenti risolti',
  'insert-comment-next-all': 'Vai al commento successivo',
  'insert-comment-previous-all': 'Vai al commento precedente',
  'insert-comment-list-all': 'Visualizza elenco commenti',
};

export const provideItalianNgxEditor = () => {
  return importProvidersFrom(
    NgxEditorModule.forRoot({
      locals: NgxEditorItalianLocale,
    })
  );
};
