import { CommonModule } from '@angular/common';
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { TailwindFormsModule } from '../tailwind-forms/tailwind-forms.module';

@Component({
  selector: 'notify-icon-selector',
  standalone: true,
  imports: [CommonModule, TailwindFormsModule],
  templateUrl: './icon-selector.component.html',
  styleUrls: ['./icon-selector.component.scss'],
})
export class IconSelectorComponent implements OnInit {
  @Output() public icon = new EventEmitter<(typeof AVAILABLE_ICONS)[0]>();

  public hideSelector = false;

  public availableIcons = AVAILABLE_ICONS;

  public currentIcon = {
    expanded: 'Question',
    name: 'question',
    tags: [],
    set: 'octicons',
    score: 10,
  };

  public ngOnInit() {
    this._loadScript();
    this.icon.emit(this.currentIcon);
  }

  public genIconUrl(icon: (typeof AVAILABLE_ICONS)[0]) {
    return `https://s2.svgbox.net/${icon.set}.svg?ic=${icon.name}`;
  }

  public setIcon(icon: (typeof AVAILABLE_ICONS)[0]) {
    this.currentIcon = icon;
    this.icon.emit(this.currentIcon);
    this.hideSelector = true;
  }

  private _loadScript() {
    console.log('preparing to load...');
    const node = document.createElement('script');
    node.src = 'https://unpkg.com/external-svg-loader@latest/svg-loader.min.js';
    node.type = 'text/javascript';
    node.async = true;
    node.charset = 'utf-8';
    document.getElementsByTagName('head')[0].appendChild(node);
  }
}

const AVAILABLE_ICONS = [
  {
    expanded: 'About Dot Me',
    name: 'about-dot-me',
    tags: [],
    set: 'social',
    score: 10,
  },
  { expanded: 'Airbnb', name: 'airbnb', tags: [], set: 'social', score: 1 },
  { expanded: 'Amazon', name: 'amazon', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Angellist',
    name: 'angellist',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Apple Podcasts',
    name: 'apple-podcasts',
    tags: [],
    set: 'social',
    score: 7.142857142857143,
  },
  { expanded: 'Apple', name: 'apple', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Applemusic',
    name: 'applemusic',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Applepay',
    name: 'applepay',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Appletv', name: 'appletv', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Appstore',
    name: 'appstore',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  { expanded: 'Askfm', name: 'askfm', tags: [], set: 'social', score: 20 },
  { expanded: 'Behance', name: 'behance', tags: [], set: 'social', score: 1 },
  { expanded: 'Bing', name: 'bing', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Bitbucket',
    name: 'bitbucket',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Blogger', name: 'blogger', tags: [], set: 'social', score: 1 },
  { expanded: 'Box', name: 'box', tags: [], set: 'social', score: 100 },
  { expanded: 'Brave', name: 'brave', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Buzzfeed',
    name: 'buzzfeed',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Codechef',
    name: 'codechef',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Codepen', name: 'codepen', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Coinbase',
    name: 'coinbase',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  {
    expanded: 'Coursera',
    name: 'coursera',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  {
    expanded: 'Crunchbase',
    name: 'crunchbase',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Crunchyroll',
    name: 'crunchyroll',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Dailymotion',
    name: 'dailymotion',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Dev Dot To',
    name: 'dev-dot-to',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  {
    expanded: 'Deviantart',
    name: 'deviantart',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Digg', name: 'digg', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Discord',
    name: 'discord',
    tags: [],
    set: 'social',
    score: 14.285714285714286,
  },
  {
    expanded: 'Discourse',
    name: 'discourse',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Disqus',
    name: 'disqus',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  {
    expanded: 'Dribbble',
    name: 'dribbble',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Dropbox',
    name: 'dropbox',
    tags: [],
    set: 'social',
    score: 20,
  },
  {
    expanded: 'Duckduckgo',
    name: 'duckduckgo',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Ebay', name: 'ebay', tags: [], set: 'social', score: 1 },
  { expanded: 'Etsy', name: 'etsy', tags: [], set: 'social', score: 25 },
  {
    expanded: 'Eventbrite',
    name: 'eventbrite',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Evernote',
    name: 'evernote',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Facebook',
    name: 'facebook',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Fandom', name: 'fandom', tags: [], set: 'social', score: 25 },
  { expanded: 'Firefox', name: 'firefox', tags: [], set: 'social', score: 1 },
  { expanded: 'Fitbit', name: 'fitbit', tags: [], set: 'social', score: 1 },
  { expanded: 'Flattr', name: 'flattr', tags: [], set: 'social', score: 1 },
  { expanded: 'Flickr', name: 'flickr', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Foursquare',
    name: 'foursquare',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Freelancer',
    name: 'freelancer',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Genius',
    name: 'genius',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  { expanded: 'Ghost', name: 'ghost', tags: [], set: 'social', score: 20 },
  { expanded: 'Giphy', name: 'giphy', tags: [], set: 'social', score: 1 },
  { expanded: 'Github', name: 'github', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Glassdoor',
    name: 'glassdoor',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  { expanded: 'Gmail', name: 'gmail', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Goodreads',
    name: 'goodreads',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Google Podcasts',
    name: 'google-podcasts',
    tags: [],
    set: 'social',
    score: 6.666666666666667,
  },
  { expanded: 'Google', name: 'google', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Googlecalendar',
    name: 'googlecalendar',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Googlechrome',
    name: 'googlechrome',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Googledrive',
    name: 'googledrive',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Googleearth',
    name: 'googleearth',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Googlenews',
    name: 'googlenews',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Googlepay',
    name: 'googlepay',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Googleplay',
    name: 'googleplay',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Googletranslate',
    name: 'googletranslate',
    tags: [],
    set: 'social',
    score: 6.666666666666667,
  },
  { expanded: 'Gumroad', name: 'gumroad', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Hackerone',
    name: 'hackerone',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Hackerrank',
    name: 'hackerrank',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Imdb', name: 'imdb', tags: [], set: 'social', score: 1 },
  { expanded: 'Imgur', name: 'imgur', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Instacart',
    name: 'instacart',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Instagram',
    name: 'instagram',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Instapaper',
    name: 'instapaper',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Itunes',
    name: 'itunes',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  { expanded: 'Kaggle', name: 'kaggle', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Kickstarter',
    name: 'kickstarter',
    tags: [],
    set: 'social',
    score: 9.090909090909092,
  },
  { expanded: 'Line', name: 'line', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Linkedin',
    name: 'linkedin',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Livejournal',
    name: 'livejournal',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Lyft', name: 'lyft', tags: [], set: 'social', score: 1 },
  { expanded: 'Medium', name: 'medium', tags: [], set: 'social', score: 1 },
  { expanded: 'Meetup', name: 'meetup', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Messenger',
    name: 'messenger',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Myspace',
    name: 'myspace',
    tags: [],
    set: 'social',
    score: 14.285714285714286,
  },
  { expanded: 'Netflix', name: 'netflix', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Nextdoor',
    name: 'nextdoor',
    tags: [],
    set: 'social',
    score: 20,
  },
  { expanded: 'Opera', name: 'opera', tags: [], set: 'social', score: 1 },
  { expanded: 'Patreon', name: 'patreon', tags: [], set: 'social', score: 1 },
  { expanded: 'Paypal', name: 'paypal', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Pinboard',
    name: 'pinboard',
    tags: [],
    set: 'social',
    score: 14.285714285714286,
  },
  {
    expanded: 'Pinterest',
    name: 'pinterest',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  { expanded: 'Pocket', name: 'pocket', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Producthunt',
    name: 'producthunt',
    tags: [],
    set: 'social',
    score: 1,
  },
  {
    expanded: 'Protonmail',
    name: 'protonmail',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Quora', name: 'quora', tags: [], set: 'social', score: 1 },
  { expanded: 'Reddit', name: 'reddit', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Rss',
    name: 'rss',
    tags: [],
    set: 'social',
    score: 33.333333333333336,
  },
  {
    expanded: 'Safari',
    name: 'safari',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  {
    expanded: 'Scribd',
    name: 'scribd',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  {
    expanded: 'Signal',
    name: 'signal',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  { expanded: 'Skype', name: 'skype', tags: [], set: 'social', score: 20 },
  { expanded: 'Slack', name: 'slack', tags: [], set: 'social', score: 20 },
  {
    expanded: 'Slideshare',
    name: 'slideshare',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Snapchat',
    name: 'snapchat',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  {
    expanded: 'Soundcloud',
    name: 'soundcloud',
    tags: [],
    set: 'social',
    score: 10,
  },
  {
    expanded: 'Spotify',
    name: 'spotify',
    tags: [],
    set: 'social',
    score: 14.285714285714286,
  },
  {
    expanded: 'Stackexchange',
    name: 'stackexchange',
    tags: [],
    set: 'social',
    score: 7.6923076923076925,
  },
  {
    expanded: 'Stackoverflow',
    name: 'stackoverflow',
    tags: [],
    set: 'social',
    score: 7.6923076923076925,
  },
  { expanded: 'Steam', name: 'steam', tags: [], set: 'social', score: 20 },
  {
    expanded: 'Strava',
    name: 'strava',
    tags: [],
    set: 'social',
    score: 16.666666666666668,
  },
  {
    expanded: 'Telegram',
    name: 'telegram',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Tiktok', name: 'tiktok', tags: [], set: 'social', score: 1 },
  { expanded: 'Tinder', name: 'tinder', tags: [], set: 'social', score: 1 },
  { expanded: 'Tor', name: 'tor', tags: [], set: 'social', score: 1 },
  { expanded: 'Trello', name: 'trello', tags: [], set: 'social', score: 1 },
  { expanded: 'Tumblr', name: 'tumblr', tags: [], set: 'social', score: 1 },
  { expanded: 'Twitch', name: 'twitch', tags: [], set: 'social', score: 1 },
  { expanded: 'Twitter', name: 'twitter', tags: [], set: 'social', score: 1 },
  { expanded: 'Uber', name: 'uber', tags: [], set: 'social', score: 1 },
  { expanded: 'Udacity', name: 'udacity', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Unsplash',
    name: 'unsplash',
    tags: [],
    set: 'social',
    score: 12.5,
  },
  { expanded: 'Upwork', name: 'upwork', tags: [], set: 'social', score: 1 },
  { expanded: 'Venmo', name: 'venmo', tags: [], set: 'social', score: 1 },
  { expanded: 'Viber', name: 'viber', tags: [], set: 'social', score: 1 },
  { expanded: 'Vimeo', name: 'vimeo', tags: [], set: 'social', score: 1 },
  { expanded: 'Wattpad', name: 'wattpad', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Wikipedia',
    name: 'wikipedia',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Wix', name: 'wix', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Wordpress',
    name: 'wordpress',
    tags: [],
    set: 'social',
    score: 11.11111111111111,
  },
  {
    expanded: 'Ycombinator',
    name: 'ycombinator',
    tags: [],
    set: 'social',
    score: 1,
  },
  { expanded: 'Yelp', name: 'yelp', tags: [], set: 'social', score: 1 },
  { expanded: 'Youtube', name: 'youtube', tags: [], set: 'social', score: 1 },
  {
    expanded: 'Youtubemusic',
    name: 'youtubemusic',
    tags: [],
    set: 'social',
    score: 8.333333333333334,
  },
  { expanded: 'Zoom', name: 'zoom', tags: [], set: 'social', score: 1 },
];
