require_relative '../../../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityMedia', :path => '../../../../../node_modules/@capacitor-community/media'
  pod 'CapacitorCommunityScreenBrightness', :path => '../../../../../node_modules/@capacitor-community/screen-brightness'
  pod 'CapacitorApp', :path => '../../../../../node_modules/@capacitor/app'
  pod 'CapacitorFilesystem', :path => '../../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../../../node_modules/@capacitor/haptics'
  pod 'CapacitorStatusBar', :path => '../../../../../node_modules/@capacitor/status-bar'
  pod 'CapawesomeTeamCapacitorNfc', :path => '../../../../../node_modules/@capawesome-team/capacitor-nfc'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'CapacitorFilesystem', :path => '../../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorCommunityScreenBrightness', :path => '../../../../../node_modules/@capacitor-community/screen-brightness'
  pod 'CapacitorCommunityMedia', :path => '../../../../../node_modules/@capacitor-community/media'
  pod 'CapawesomeTeamCapacitorNfc', :path => '../../../../../node_modules/@capawesome-team/capacitor-nfc'
  pod 'CapacitorCamera', :path => '../../../../../node_modules/@capacitor/camera'
  pod 'CapacitorSuppressLongpressGesture' , :path => '../../../../../node_modules/capacitor-suppress-longpress-gesture'
  pod 'CapacitorActionSheet', :path => '../../../../../node_modules/@capacitor/action-sheet'
  pod 'CapacitorStatusBar', :path => '../../../../../node_modules/@capacitor/status-bar'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
